// src/components/PptEditor.js

import { useState, useEffect } from 'react';
import { SketchPicker } from 'react-color';
import toast from 'react-hot-toast';
import RichTextEditor from './RichTextEditor';

// Helper to parse CSV text into an array of arrays for the table
function parseCsvForTable(csvText) {
    if (!csvText || !csvText.trim()) return null;
    return csvText.trim().split('\n').map(row => row.split(',').map(cell => cell.trim()));
}

// Helper to parse the Rich Text Editor's HTML output
function convertHtmlToPptxTextObjects(html) {
    if (!html || typeof document === 'undefined') return [];
    const parser = new DOMParser();
    const doc = parser.parseFromString(html, 'text/html');
    const pptxObjects = [];
    doc.body.childNodes.forEach(node => {
        if (['P', 'H1', 'H2', 'H3', 'LI', 'UL', 'OL'].includes(node.nodeName)) {
            const processNode = (n) => {
                const textContent = n.textContent.trim();
                if (textContent) {
                    const isBold = n.querySelector('strong, b') !== null;
                    pptxObjects.push({
                        text: textContent,
                        options: {
                            bold: isBold,
                            bullet: n.nodeName === 'LI' || (n.parentElement && n.parentElement.nodeName === 'LI'),
                            breakLine: n.nodeName.startsWith('H') || n.nodeName === 'P',
                        }
                    });
                }
            };
            if (node.nodeName === 'UL' || node.nodeName === 'OL') {
                Array.from(node.children).forEach(li => processNode(li));
            } else {
                processNode(node);
            }
        }
    });
    return pptxObjects;
}

export default function PptEditor({ generatedContent, botName, PptxGenJS, onClose }) {
    const [title, setTitle] = useState(botName || 'Generated Presentation');
    const [slides, setSlides] = useState([]);
    const [selectedSlideId, setSelectedSlideId] = useState(null);

    useEffect(() => {
        const initialSlides = generatedContent.trim().split(/\n---\n/).map((text, index) => ({
            id: Date.now() + index,
            title: { text: text.split('\n')[0] || `Slide ${index + 1}`, fontSize: 32, color: '363636', bold: true },
            body: { fontSize: 18, color: '494949' }, // Body now has its own formatting state
            bodyHtml: `<p>${text.split('\n').slice(1).join('</p><p>')}</p>`,
            imageUrl: '',
            tableData: '',
        }));
        setSlides(initialSlides);
        if (initialSlides.length > 0) {
            setSelectedSlideId(initialSlides[0].id);
        }
    }, [generatedContent]);

    const handleUpdateSlide = (id, field, property, value) => {
        setSlides(slides.map(slide => slide.id === id ? { ...slide, [field]: { ...slide[field], [property]: value } } : slide));
    };
    
    const handleUpdateStringField = (id, field, value) => {
        setSlides(slides.map(slide => slide.id === id ? { ...slide, [field]: value } : slide));
    };

    const addSlide = () => {
        const newSlide = { id: Date.now(), title: { text: `New Slide`, fontSize: 32, color: '363636', bold: true }, body: { fontSize: 18, color: '494949' }, bodyHtml: '<p></p>', imageUrl: '', tableData: '' };
        setSlides([...slides, newSlide]);
        setSelectedSlideId(newSlide.id);
    };

    const deleteSlide = (idToDelete) => {
        const newSlides = slides.filter(slide => slide.id !== idToDelete);
        setSlides(newSlides);
        if (selectedSlideId === idToDelete) {
            setSelectedSlideId(newSlides.length > 0 ? newSlides[0].id : null);
        }
    };

    const handleGeneratePpt = () => {
        if (!PptxGenJS) { toast.error("Presentation library not loaded."); return; }
        const toastId = toast.loading("Generating presentation...");
        try {
            let pres = new PptxGenJS();
            const brandColor = 'cf3222', defaultTextColor = '363636', backgroundColor = 'F1F1F1';

            pres.defineSlideMaster({ title: 'CONTENT_MASTER', background: { color: backgroundColor }, objects: [ { placeholder: { options: { name: 'title', type: 'title', x: 0.5, y: 0.25, w: 9, h: 1, color: brandColor, fontSize: 32, bold: true } } }, { placeholder: { options: { name: 'body', type: 'body', x: 0.5, y: 1.5, w: 5, h: 3.5, color: defaultTextColor, fontSize: 18 } } }, { rect: { x: 0, y: "95%", w: "100%", h: "5%", fill: { color: brandColor } } }, { text: { text: "Generated by Digital Lesson", options: { x: 0, y: "95%", w: "100%", align: "center", color: "FFFFFF", fontSize: 10 } } }] });
            
            pres.addSlide().addText(title, { x: '5%', y: '40%', w: '90%', fontSize: 44, bold: true, align: 'center', color: defaultTextColor });

            slides.forEach(slide => {
                const contentSlide = pres.addSlide({ masterName: 'CONTENT_MASTER' });
                contentSlide.addText(slide.title.text, { ...slide.title, placeholder: 'title' });
                
                const tableRows = parseCsvForTable(slide.tableData);
                if (tableRows) {
                    contentSlide.addTable(tableRows, { x: 0.5, y: 1.5, w: 9, autoPage: true, colW: [3, 3, 3], head: { fill: { color: brandColor }, color: 'FFFFFF' }, row: { fill: { color: 'F7F7F7' } } });
                } else {
                    const bodyObjects = convertHtmlToPptxTextObjects(slide.bodyHtml);
                    if (bodyObjects.length > 0) {
                        const styledBodyObjects = bodyObjects.map(obj => ({ ...obj, options: { ...obj.options, color: slide.body.color, fontSize: slide.body.fontSize } }));
                        contentSlide.addText(styledBodyObjects, { placeholder: 'body' });
                    }
                }

                if (slide.imageUrl) {
                    contentSlide.addImage({ path: slide.imageUrl, x: 6.0, y: 1.5, w: 3.5, h: 3.5 });
                }
            });

            pres.writeFile({ fileName: `${title.replace(/ /g, '_')}.pptx` });
            toast.success("Presentation downloaded!", { id: toastId });
            onClose();
        } catch (error) {
            console.error(error);
            toast.error("Failed to generate presentation.", { id: toastId });
        }
    };

    const selectedSlide = slides.find(s => s.id === selectedSlideId);

    return (
        <div className="modal-overlay active">
            <div className="modal-content" style={{ display: 'flex', maxWidth: '85vw', width: '1200px', height: '80vh', padding: 0, overflow: 'hidden' }}>
                <div className="ppt-editor-sidebar" style={{ width: '250px', display: 'flex', flexDirection: 'column' }}>
                    <h3 style={{ padding: '20px 20px 10px 20px', flexShrink: 0 }}>Slides</h3>
                    <div style={{ flexGrow: 1, overflowY: 'auto', padding: '10px 20px' }}>
                        {slides.map((slide, index) => (
                            <div key={slide.id} onClick={() => setSelectedSlideId(slide.id)} 
                                style={{ padding: '10px', marginBottom: '10px', borderRadius: '8px', cursor: 'pointer', border: `2px solid ${slide.id === selectedSlideId ? 'var(--brand-color)' : 'transparent'}`, position: 'relative', background: 'rgba(0,0,0,0.1)' }}>
                                <p style={{ margin: 0, fontWeight: 'bold', whiteSpace: 'nowrap', overflow: 'hidden', textOverflow: 'ellipsis' }}>{index + 1}. {slide.title.text}</p>
                                <button onClick={(e) => { e.stopPropagation(); deleteSlide(slide.id); }} style={{ position: 'absolute', top: '2px', right: '2px', background: 'none', border: 'none', color: 'inherit', cursor: 'pointer', fontSize: '16px', lineHeight: 1 }}>&times;</button>
                            </div>
                        ))}
                    </div>
                    <div style={{ padding: '20px', borderTop: '1px solid var(--border-light)', flexShrink: 0 }}>
                        <button className="cta-button" onClick={addSlide} style={{ width: '100%' }}>Add Slide</button>
                    </div>
                </div>

                <div style={{ flex: 1, display: 'flex', flexDirection: 'column', padding: '20px' }}>
                    <div className="form-field" style={{ flexShrink: 0 }}><label>Presentation Title</label><input type="text" value={title} onChange={(e) => setTitle(e.target.value)} /></div>
                    <hr style={{ width: '100%', border: 'none', borderTop: '1px solid var(--border-light)', margin: '20px 0' }} />
                    {selectedSlide ? (
                        <div style={{ flex: 1, display: 'grid', gridTemplateColumns: '2fr 1fr', gap: '20px', overflow: 'hidden' }}>
                            <div style={{ display: 'flex', flexDirection: 'column', gap: '20px', overflowY: 'auto', paddingRight: '10px' }}>
                                <h4>Editing Slide {slides.findIndex(s => s.id === selectedSlideId) + 1}</h4>
                                <div className="form-field"><label>Slide Title</label><input type="text" value={selectedSlide.title.text} onChange={e => handleUpdateSlide(selectedSlide.id, 'title', 'text', e.target.value)} /></div>
                                
                                <div className="form-field" style={{ flex: 1, display: 'flex', flexDirection: 'column' }}><label>Slide Body</label>
                                    <RichTextEditor 
                                        value={selectedSlide.bodyHtml} 
                                        onChange={html => handleUpdateStringField(selectedSlide.id, 'bodyHtml', html)} 
                                    />
                                </div>
                                
                                <div className="form-field"><label>Image URL (Optional)</label><input type="text" placeholder="https://example.com/image.png" value={selectedSlide.imageUrl} onChange={e => handleUpdateStringField(selectedSlide.id, 'imageUrl', e.target.value)} /></div>
                                <div className="form-field"><label>Table Data as CSV (Optional)</label><textarea placeholder="Header 1,Header 2&#10;Data A,Data B" value={selectedSlide.tableData} onChange={e => handleUpdateStringField(selectedSlide.id, 'tableData', e.target.value)} style={{ minHeight: '100px', resize: 'vertical', fontFamily: 'monospace' }} /></div>
                            </div>
                            <div style={{ overflowY: 'auto', paddingRight: '10px' }}>
                                <h4>Formatting</h4>
                                <h5>Title</h5>
                                <label>Font Size: </label>
                                <input type="number" value={selectedSlide.title.fontSize} onChange={e => handleUpdateSlide(selectedSlide.id, 'title', 'fontSize', parseInt(e.target.value))} style={{width: '60px', marginBottom: '10px'}}/>
                                <br />
                                <label>Color:</label>
                                <SketchPicker 
                                    disableAlpha={true} 
                                    presetColors={['#cf3222', '#363636', '#FFFFFF', '#808080']} 
                                    color={`#${selectedSlide.title.color}`} 
                                    onChangeComplete={color => handleUpdateSlide(selectedSlide.id, 'title', 'color', color.hex.replace('#', ''))} 
                                />
                                
                                <h5 style={{marginTop: '20px'}}>Body</h5>
                                <label>Font Size: </label>
                                <input type="number" value={selectedSlide.body.fontSize} onChange={e => handleUpdateSlide(selectedSlide.id, 'body', 'fontSize', parseInt(e.target.value))} style={{width: '60px', marginBottom: '10px'}}/>
                                <br />
                                <label>Color:</label>
                                <SketchPicker 
                                    disableAlpha={true} 
                                    presetColors={['#cf3222', '#494949', '#FFFFFF', '#808080']} 
                                    color={`#${selectedSlide.body.color}`} 
                                    onChangeComplete={color => handleUpdateSlide(selectedSlide.id, 'body', 'color', color.hex.replace('#', ''))} 
                                />
                            </div>
                        </div>
                    ) : <p style={{textAlign: 'center', alignSelf: 'center'}}>Select a slide to edit or add a new one.</p>}
                     <div className="edit-form-actions" style={{ justifyContent: 'flex-end', flexShrink: 0, marginTop: '20px' }}>
                        <button type="button" className="details-link" onClick={onClose}>Cancel</button>
                        <button type="button" className="cta-button" onClick={handleGeneratePpt} disabled={slides.length === 0}>Generate & Download PPT</button>
                    </div>
                </div>
            </div>
        </div>
    );
}