// src/pages/share/[noteId].js

import Head from 'next/head';
import { PrismaClient } from '@prisma/client';
import ReactMarkdown from 'react-markdown';
import Layout from '../../components/Layout';

const prisma = new PrismaClient();

// This is the public page component
export default function SharedNotePage({ note, error }) {
    if (error) {
        return (
            <Layout>
                <div className="container" style={{ textAlign: 'center', paddingTop: '80px', paddingBottom: '80px' }}>
                    <h1>Note Not Found</h1>
                    <p>{error}</p>
                </div>
            </Layout>
        );
    }

    const formattedDate = new Date(note.createdAt).toLocaleDateString('en-US', {
        year: 'numeric',
        month: 'long',
        day: 'numeric',
    });

    return (
        <Layout>
            <Head>
                <title>{`Shared Note from ${note.botName}`}</title>
                <meta name="description" content="A shared note generated by an AI agent." />
            </Head>
            <div className="container" style={{ maxWidth: '800px', paddingTop: '60px', paddingBottom: '80px' }}>
                <div className="shared-note-header">
                    <h1 style={{ marginBottom: '8px' }}>AI-Generated Content</h1>
                    <p style={{ color: 'var(--text-secondary-dark)', marginTop: 0 }}>
                        Created with the <strong>{note.botName}</strong> agent on {formattedDate}.
                    </p>
                </div>
                <div className="shared-note-content" style={{ 
                    padding: '24px', 
                    background: 'var(--card-bg-dark)', 
                    border: '1px solid var(--border-dark)', 
                    borderRadius: 'var(--border-radius-lg)',
                    marginTop: '32px'
                }}>
                    <ReactMarkdown>{note.content}</ReactMarkdown>
                </div>
            </div>
        </Layout>
    );
}

// This function runs on the server for every request to this page
export async function getServerSideProps(context) {
    const { noteId } = context.params;

    try {
        const note = await prisma.sharedNote.findUnique({
            where: { id: noteId },
        });

        if (!note) {
            return {
                props: { error: 'This link may be invalid or the note has been deleted.' },
            };
        }

        // Convert the Date object to a serializable string
        const serializableNote = {
            ...note,
            createdAt: note.createdAt.toISOString(),
        };

        return {
            props: { note: serializableNote },
        };
    } catch (error) {
        return {
            props: { error: 'A database error occurred.' },
        };
    }
}